import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('smartesco_lang');
    return saved ? saved : 'PT';
  });

  const toggleLanguage = () => {
    setLanguage((prev) => {
      const next = prev === 'PT' ? 'EN' : 'PT';
      localStorage.setItem('smartesco_lang', next);
      return next;
    });
  };

  // Translations dictionary for general UI elements
  const translations = {
    PT: {
      // Navbar & Footer
      nav_inicio: "Início",
      nav_servicos: "Serviços",
      nav_projetos: "Projetos",
      nav_analise: "Painel de Análise",
      nav_contato: "Contato",
      footer_desc: "Engenharia eletrônica e software para o futuro da indústria.",
      footer_contato: "Contato",
      footer_redes: "Redes Sociais",
      footer_direitos: "Todos os direitos reservados.",
      
      // Home
      home_badge: "Inovação B2B",
      home_hero_title: "Soluções Avançadas em Eletrônica e Software para Energia",
      home_hero_subtitle: "Desenvolvemos infraestrutura inteligente com IoT, Edge AI e Smart Grids para otimizar operações no setor energético e industrial.",
      home_hero_btn: "Conheça Nossas Soluções",
      home_feat_title: "Transformando dados em eficiência operacional",
      home_feat_desc: "A SmartESCO atua na interseção entre hardware robusto e software inteligente. Nossa missão é modernizar a infraestrutura de energia através de tecnologias de ponta que garantem confiabilidade, segurança e otimização de recursos.",
      home_feat_item1: "Hardware customizado para ambientes industriais",
      home_feat_item2: "Processamento de dados na borda (Edge AI)",
      home_feat_item3: "Integração perfeita com sistemas legados",
      home_feat_link: "Ver nossos projetos",
      home_card_hw: "Hardware",
      home_card_hw_desc: "Desenvolvimento de placas e sensores industriais.",
      home_card_iot: "IoT & Edge",
      home_card_iot_desc: "Redes distribuídas e inteligência local.",
      home_card_sg: "Smart Grids",
      home_card_sg_desc: "Gestão avançada de distribuição de energia.",
      home_card_stat: "Anos de pesquisa e inovação aplicada.",

      // Servicos
      serv_hero_title: "Nossos Serviços",
      serv_hero_desc: "Desenvolvemos soluções em eletrônica e software para setores críticos.",
      serv_card_el: "Eletrônica",
      serv_card_el_desc: "Projetos customizados de hardware para IoT, Edge AI e smart grids.",
      serv_card_sw: "Software",
      serv_card_sw_desc: "Plataformas robustas para visão computacional e inteligência artificial.",
      serv_card_parc: "Parcerias",
      serv_card_parc_desc: "Aplicações em HPC, robótica e sistemas para energia e óleo&gás.",
      serv_faq_title: "Dúvidas Frequentes",
      serv_faq_q1: "Quais serviços oferecemos?",
      serv_faq_a1: "Desenvolvemos eletrônica customizada e software para edge AI e IoT.",
      serv_faq_q2: "Com quem trabalhamos?",
      serv_faq_a2: "Atendemos empresas dos setores elétrico, energia e óleo & gás, com parcerias acadêmicas.",
      serv_faq_q3: "Quais tecnologias utilizamos?",
      serv_faq_a3: "Aplicamos IoT, edge AI, smart grid, HPC, robótica, visão computacional e IA em nossos projetos.",
      serv_faq_q4: "Como funciona a parceria acadêmica?",
      serv_faq_a4: "Nossa equipe colabora com laboratórios da Coppe/UFRJ, UFF, USP e UERJ.",
      serv_faq_q5: "Qual o diferencial da SmartESCO?",
      serv_faq_a5: "Unimos expertise em hardware e software para soluções sob medida e inovadoras.",

      // Contato
      cont_hero_title: "Contato",
      cont_hero_desc: "Fale conosco para projetos de eletrônica customizada, Edge AI e parcerias acadêmicas.",
      cont_section_title: "Localização e Inovação",
      cont_body_text: "Estamos localizados em Petrópolis, na região serrana do Rio de Janeiro, um importante polo de inovação e tecnologia. Nossa sede nos permite desenvolver soluções inteligentes com foco em excelência e agilidade.",
      cont_address: "Endereço",
      cont_hours: "Horário de Atendimento",
      cont_hours_desc: "Segunda a Sexta: 08:00 - 18:00",
      cont_email_tel: "Email e Telefone",
      cont_form_title: "Envie uma Mensagem",
      cont_form_name: "Seu nome",
      cont_form_name_ph: "Digite seu nome",
      cont_form_email: "Seu e-mail",
      cont_form_email_ph: "Digite seu e-mail",
      cont_form_msg: "Mensagem",
      cont_form_msg_ph: "Escreva sua mensagem",
      cont_form_btn: "Enviar Mensagem",

      // Projetos / ProjetoDetalhes
      proj_hero_title: "Projetos de P&D do SmartESCO Hub",
      proj_hero_desc: "Confira a excelência das soluções e projetos de Pesquisa & Desenvolvimento que impulsionam o futuro da eficiência operacional e energética.",
      proj_btn_details: "Ver detalhes",
      proj_cta_title: "Tem um projeto de P&D ou Inovação?",
      proj_cta_desc: "Unimos hardware robusto, Edge AI e plataformas de software inteligentes para co-criar soluções de alto impacto. Vamos conversar!",
      proj_cta_btn: "Fale com Nossos Especialistas",
      
      det_overview: "OVERVIEW DO PROJETO",
      det_resumo: "Resumo",
      det_resultados: "Resultados & Publicações",
      det_titulo: "DETALHES",
      det_lbl_titulo: "Título",
      det_lbl_lab: "Laboratório",
      det_lbl_coord: "Coordenador",
      det_lbl_inicio: "Início",
      det_lbl_termino: "Término",
      det_lbl_status: "Status",
      det_lbl_financ: "Financiador",
      det_cta_title: "Deseja uma solução similar?",
      det_cta_desc: "Conecte o seu negócio com os nossos especialistas e laboratórios de pesquisa de ponta.",
      det_cta_btn: "Falar Conosco",
      det_related: "PROJETOS RELACIONADOS",
      det_back: "Voltar aos Projetos",
      det_not_found: "Projeto não encontrado.",
      
      // AnaliseConsumo
      an_title: "Painel de Análise Energética",
      an_subtitle: "Insights avançados, detecção de picos de demanda e simulações tarifárias para eficiência ativa.",
      an_uc_select: "Selecione a Unidade Consumidora:",
      an_tab_geral: "Visão Geral",
      an_tab_picos: "Detecção de Picos",
      an_tab_tarifaria: "Simulador de Tarifas",
      an_tab_eficiencia: "Indicadores de Eficiência",
      an_tab_previsao: "Previsões & Clima",
      an_tab_insights: "Central de Insights",
      an_card_total: "Consumo Total",
      an_card_media: "Média Diária",
      an_card_max: "Consumo Máximo",
      an_card_min: "Consumo Mínimo",
      an_card_profile: "Perfil de Carga",
      an_chart_title_30d: "Consumo Histórico de Energia - Últimos 30 Dias",
      an_chart_desc_30d: "Curva diária de consumo de energia elétrica em kWh",
      an_chart_title_hour: "Perfil de Carga Horário Médio",
      an_chart_desc_hour: "Comportamento do consumo de energia ao longo das 24 horas",
      an_chart_title_peaks: "Detecção de Picos de Demanda (Acima do Limite)",
      an_chart_desc_peaks: "Identificação automática de anomalias e surtos de consumo",
      an_threshold_limit: "Limite de Alerta de Demanda",
      an_peaks_detected: "Picos de demanda detectados no período:",
      an_peaks_none: "Nenhum pico de demanda fora do limite foi detectado.",
      an_peak_at: "Pico em",
      an_sim_title: "Simulação de Estruturas Tarifárias",
      an_sim_desc: "Simulação baseada no perfil de consumo horário estimado das últimas 24h.",
      an_sim_curr: "Consumo Total Simulador (24h)",
      an_sim_conv: "Custo Estimado Convencional (Tarifa B)",
      an_sim_white: "Custo Estimado Tarifa Branca",
      an_sim_savings: "Economia Mensal Estimada com Tarifa Branca:",
      an_sim_warning: "Atenção: A viabilidade da Tarifa Branca depende da concentração do seu consumo fora dos horários de ponta (18h às 21h).",
      an_eff_title: "Indicadores de Eficiência Energética",
      an_eff_load_factor: "Fator de Carga (FC)",
      an_eff_load_factor_desc: "Relação entre o consumo médio e o consumo máximo registrado. Quanto mais próximo de 1.0, mais estável é a demanda da unidade.",
      an_eff_idle: "Consumo de Carga Ociosa (Linha de Base)",
      an_eff_idle_desc: "Estimativa de consumo mínimo em períodos de inatividade (madrugadas ou finais de semana). Representa oportunidades de desligamento preventivo.",
      an_eff_distribution: "Distribuição do Consumo de Carga",
      an_eff_dist_desc: "Proporção do consumo energético classificado por níveis de carga",
      an_eff_cat_alta: "Alta Carga",
      an_eff_cat_media: "Média Carga",
      an_eff_cat_baixa: "Baixa Carga",
      an_prev_title: "Previsão Estatística de Demanda (Próximos 4 Dias)",
      an_prev_desc: "Cálculo probabilístico com base em regressão linear local e sazonalidade diária.",
      an_prev_cost: "Custo Projetado (Próximos 30 Dias): R$",
      an_prev_peak_warning: "Alerta de Risco de Pico: Alta probabilidade de ultrapassar limite de demanda no período projetado.",
      an_prev_peak_ok: "Estabilidade: Projeções indicam comportamento dentro dos limites operacionais seguros.",
      an_clim_title: "Correlação Consumo vs. Temperatura Ambiente",
      an_clim_desc: "Análise de sensibilidade térmica do consumo (refrigeração/climatização).",
      an_clim_coef: "Coeficiente de Correlação de Pearson (R):",
      an_clim_strong: "Forte correlação direta: o aumento da temperatura ambiente eleva significativamente o consumo elétrico (HVAC ativo).",
      an_clim_moderate: "Correlação moderada: variação térmica influencia o consumo, mas outros fatores operacionais são preponderantes.",
      an_clim_weak: "Fraca correlação: o consumo da unidade é praticamente independente das variações climáticas locais.",
      an_insights_title: "Recomendações e Plano de Ação Personalizado",
      an_insights_desc: "Dicas geradas automaticamente com base no perfil de consumo e anomalias detectadas.",
      an_alert_list_title: "Alertas Ativos do Sistema",
    },
    EN: {
      // Navbar & Footer
      nav_inicio: "Home",
      nav_servicos: "Services",
      nav_projetos: "Projects",
      nav_analise: "Analysis Panel",
      nav_contato: "Contact",
      footer_desc: "Electronic engineering and software for the future of industry.",
      footer_contato: "Contact",
      footer_redes: "Social Media",
      footer_direitos: "All rights reserved.",
      
      // Home
      home_badge: "B2B Innovation",
      home_hero_title: "Advanced Electronics and Software Solutions for Energy",
      home_hero_subtitle: "We develop intelligent infrastructure with IoT, Edge AI, and Smart Grids to optimize operations in the energy and industrial sectors.",
      home_hero_btn: "Discover Our Solutions",
      home_feat_title: "Transforming data into operational efficiency",
      home_feat_desc: "SmartESCO operates at the intersection of robust hardware and intelligent software. Our mission is to modernize energy infrastructure through cutting-edge technologies that ensure reliability, security, and resource optimization.",
      home_feat_item1: "Customized hardware for industrial environments",
      home_feat_item2: "Edge data processing (Edge AI)",
      home_feat_item3: "Seamless integration with legacy systems",
      home_feat_link: "View our projects",
      home_card_hw: "Hardware",
      home_card_hw_desc: "Development of industrial boards and sensors.",
      home_card_iot: "IoT & Edge",
      home_card_iot_desc: "Distributed networks and local intelligence.",
      home_card_sg: "Smart Grids",
      home_card_sg_desc: "Advanced energy distribution management.",
      home_card_stat: "Years of research and applied innovation.",

      // Servicos
      serv_hero_title: "Our Services",
      serv_hero_desc: "We develop electronic and software solutions for critical sectors.",
      serv_card_el: "Electronics",
      serv_card_el_desc: "Customized hardware projects for IoT, Edge AI, and smart grids.",
      serv_card_sw: "Software",
      serv_card_sw_desc: "Robust platforms for computer vision and artificial intelligence.",
      serv_card_parc: "Partnerships",
      serv_card_parc_desc: "HPC, robotics, and energy/oil & gas systems applications.",
      serv_faq_title: "Frequently Asked Questions",
      serv_faq_q1: "What services do we offer?",
      serv_faq_a1: "We develop customized electronics and software for Edge AI and IoT.",
      serv_faq_q2: "Who do we work with?",
      serv_faq_a2: "We serve companies in the electrical, energy, and oil & gas sectors, with academic partnerships.",
      serv_faq_q3: "What technologies do we use?",
      serv_faq_a3: "We apply IoT, Edge AI, smart grids, HPC, robotics, computer vision, and AI in our projects.",
      serv_faq_q4: "How does the academic partnership work?",
      serv_faq_a4: "Our team collaborates with laboratories at COPPE/UFRJ, UFF, USP, and UERJ.",
      serv_faq_q5: "What is SmartESCO's differentiator?",
      serv_faq_a5: "We combine hardware and software expertise for customized and innovative solutions.",

      // Contato
      cont_hero_title: "Contact",
      cont_hero_desc: "Contact us for customized electronics projects, Edge AI, and academic partnerships.",
      cont_section_title: "Location and Innovation",
      cont_body_text: "We are located in Petrópolis, in the mountain region of Rio de Janeiro, an important innovation and technology hub. Our headquarters allow us to develop smart solutions with focus on excellence and agility.",
      cont_address: "Address",
      cont_hours: "Business Hours",
      cont_hours_desc: "Monday to Friday: 08:00 AM - 06:00 PM",
      cont_email_tel: "Email and Phone",
      cont_form_title: "Send a Message",
      cont_form_name: "Your name",
      cont_form_name_ph: "Enter your name",
      cont_form_email: "Your e-mail",
      cont_form_email_ph: "Enter your e-mail",
      cont_form_msg: "Message",
      cont_form_msg_ph: "Write your message",
      cont_form_btn: "Send Message",

      // Projetos / ProjetoDetalhes
      proj_hero_title: "SmartESCO Hub R&D Projects",
      proj_hero_desc: "Explore the excellence of our Research & Development solutions and projects driving the future of operational and energy efficiency.",
      proj_btn_details: "View details",
      proj_cta_title: "Have a R&D or Innovation project?",
      proj_cta_desc: "We bring together robust hardware, Edge AI, and smart software platforms to co-create high-impact solutions. Let's talk!",
      proj_cta_btn: "Speak with Our Experts",
      
      det_overview: "PROJECT OVERVIEW",
      det_resumo: "Abstract",
      det_resultados: "Results & Publications",
      det_titulo: "DETAILS",
      det_lbl_titulo: "Title",
      det_lbl_lab: "Laboratory",
      det_lbl_coord: "Coordinator",
      det_lbl_inicio: "Start",
      det_lbl_termino: "End",
      det_lbl_status: "Status",
      det_lbl_financ: "Financier",
      det_cta_title: "Would you like a similar solution?",
      det_cta_desc: "Connect your business with our experts and leading research laboratories.",
      det_cta_btn: "Contact Us",
      det_related: "RELATED PROJECTS",
      det_back: "Back to Projects",
      det_not_found: "Project not found.",

      // AnaliseConsumo
      an_title: "Energy Analysis Panel",
      an_subtitle: "Advanced insights, demand peak detection, and tariff simulations for active efficiency.",
      an_uc_select: "Select Consumer Unit:",
      an_tab_geral: "Overview",
      an_tab_picos: "Peak Detection",
      an_tab_tarifaria: "Tariff Simulator",
      an_tab_eficiencia: "Efficiency Indicators",
      an_tab_previsao: "Forecasts & Climate",
      an_tab_insights: "Central Insights",
      an_card_total: "Total Consumption",
      an_card_media: "Daily Average",
      an_card_max: "Max Consumption",
      an_card_min: "Min Consumption",
      an_card_profile: "Load Profile",
      an_chart_title_30d: "Historical Energy Consumption - Last 30 Days",
      an_chart_desc_30d: "Daily electricity consumption curve in kWh",
      an_chart_title_hour: "Average Hourly Load Profile",
      an_chart_desc_hour: "Energy consumption behavior over 24 hours",
      an_chart_title_peaks: "Demand Peak Detection (Above Limit)",
      an_chart_desc_peaks: "Automatic identification of anomalies and consumption surges",
      an_threshold_limit: "Demand Alert Limit",
      an_peaks_detected: "Demand peaks detected in the period:",
      an_peaks_none: "No out-of-limit demand peaks were detected.",
      an_peak_at: "Peak at",
      an_sim_title: "Tariff Structure Simulation",
      an_sim_desc: "Simulation based on the estimated hourly consumption profile of the last 24h.",
      an_sim_curr: "Total Consumption Simulator (24h)",
      an_sim_conv: "Estimated Conventional Cost (Tariff B)",
      an_sim_white: "Estimated White Tariff Cost",
      an_sim_savings: "Estimated Monthly Savings with White Tariff:",
      an_sim_warning: "Warning: The feasibility of the White Tariff depends on your consumption concentration outside peak hours (06:00 PM to 09:00 PM).",
      an_eff_title: "Energy Efficiency Indicators",
      an_eff_load_factor: "Load Factor (LF)",
      an_eff_load_factor_desc: "Ratio between average consumption and maximum recorded consumption. The closer to 1.0, the more stable the unit's demand.",
      an_eff_idle: "Idle Load Consumption (Baseline)",
      an_eff_idle_desc: "Estimate of minimum consumption during periods of inactivity (late night or weekends). Represents preventive shutdown opportunities.",
      an_eff_distribution: "Load Consumption Distribution",
      an_eff_dist_desc: "Proportion of energy consumption classified by load levels",
      an_eff_cat_alta: "High Load",
      an_eff_cat_media: "Medium Load",
      an_eff_cat_baixa: "Low Load",
      an_prev_title: "Statistical Demand Forecast (Next 4 Days)",
      an_prev_desc: "Probabilistic calculation based on local linear regression and daily seasonality.",
      an_prev_cost: "Projected Cost (Next 30 Days): $",
      an_prev_peak_warning: "Peak Risk Alert: High probability of exceeding demand limit in projected period.",
      an_prev_peak_ok: "Stability: Projections indicate behavior within safe operational limits.",
      an_clim_title: "Correlation: Consumption vs. Ambient Temperature",
      an_clim_desc: "Thermal sensitivity analysis of consumption (cooling/climatization).",
      an_clim_coef: "Pearson Correlation Coefficient (R):",
      an_clim_strong: "Strong direct correlation: ambient temperature increase significantly raises power consumption (active HVAC).",
      an_clim_moderate: "Moderate correlation: thermal variation influences consumption, but other operational factors are predominant.",
      an_clim_weak: "Weak correlation: unit consumption is practically independent of local climate variations.",
      an_insights_title: "Recommendations and Personalized Action Plan",
      an_insights_desc: "Automatically generated tips based on consumption profile and detected anomalies.",
      an_alert_list_title: "Active System Alerts",
    }
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
